# Nivell 1

### 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

- Llista de publicacions (/posts)
- Llista d’usuaris (/users)
- Llista de tasques (/todos)

In [ ]:
%pip install requests pandas

In [4]:
import requests
import pandas as pd
import json

In [5]:
base_url = "https://jsonplaceholder.typicode.com"

# Posts
posts = requests.get(f"{base_url}/posts")

# Users
users = requests.get(f"{base_url}/users")

# Todos
todos = requests.get(f"{base_url}/todos")


posts_json = posts.json()
users_json = users.json()
todos_json = todos.json()

### 2. Mostra per pantalla:

- La quantitat total de cada recurs.
- El codi d'estat de cada petició.

In [6]:
print("POSTS")
print("Total:", len(posts_json))
print("Status:", posts.status_code)

print("\nUSERS")
print("Total:", len(users_json))
print("Status:", users.status_code)

print("\nTODOS")
print("Total:", len(todos_json))
print("Status:", todos.status_code)

POSTS
Total: 100
Status: 200

USERS
Total: 10
Status: 200

TODOS
Total: 200
Status: 200

### 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [65]:
error_response = requests.get(f"{base_url}/posts/101")
try:
    error_response.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

Error HTTP: 404 Client Error: Not Found for url: https://jsonplaceholder.typicode.com/posts/101

### 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [66]:
new_post = {
    "title": "POST ficticio",
    "body": "Publicación de prueba",
    "userId": 1
}

response_post = requests.post(
    f"{base_url}/posts",
    json=new_post
)

print("Status:", response_post.status_code)
print(response_post.json())

Status: 201
{'title': 'POST ficticio', 'body': 'Publicación de prueba', 'userId': 1, 'id': 101}

### 5. Fes una petició PATCH per modificar parcialment una publicació existent.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [67]:
update_data = {
    "title": "Título modificado"
}

response_patch = requests.patch(
    f"{base_url}/posts/1",
    json=update_data
)

print("Status:", response_patch.status_code)
print(response_patch.json())

Status: 200
{'userId': 1, 'id': 1, 'title': 'Título modificado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

### 6. Fes una petició DELETE sobre una publicació.

- Mostra la resposta JSON.
- Mostra el codi d'estat.

In [68]:
response_delete = requests.delete(f"{base_url}/posts/1")

print("Status:", response_delete.status_code)
print(response_delete.json())

Status: 200
{}

# Nivell 2

### 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

Se selecciona  Open-Meteo [Open Skills API](https://open-meteo.com/)

### 2. Llegeix la documentació de l'API:

- Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
- Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
- Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

In [59]:
url = "https://open-meteo.com/"

response = requests.get(url)

print(response.status_code)
print(response.text[:500])

200
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="/favicon.ico" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link href="/_app/immutable/entry/start.CxlFkO02.js" rel="modulepreload">
		<link href="/_app/immutable/chunks/client.CZX8HNL6.chunk.js" rel="modulepreload">
		<link href="/_app/immutable/chunks/utils.D8OTPtFe.chunk.js" rel="modulepreload">
		<link href="/_app/immutable/chunks/index-client.DZJ0adH8.chunk.js" rel="

#### Endpoints
Endpoint 1 : Permite obtener predicciones meteorológicas

/v1/forecast

Endpoint 2 : datos por ubicación
/v1/forecast?latitude=&longitude

#### Parámetros

- Current: Devuelve los datos del clima actual
- Hourly: Muestra datos por hora
- Forecast_days: días de previsión

In [47]:
url = "https://api.open-meteo.com/v1/forecast"

response = requests.get(url)

print(response.headers["Content-Type"])

application/json; charset=utf-8

### 3. Fes una petició GET senzilla:

- Mostra el codi d'estat de la resposta.
- Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [61]:
url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": 41.3851,
    "longitude": 2.1734,
    "current_weather": True
}

res = requests.get(url, params=params)

print("Status code:", res.status_code)

data = res.json()
print(data["current_weather"])

Status code: 200
{'time': '2026-06-25T12:45', 'interval': 900, 'temperature': 31.4, 'windspeed': 13.1, 'winddirection': 172, 'is_day': 1, 'weathercode': 0}

### 4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [62]:
df= pd.DataFrame([data['current_weather']])
df.head()

,time,interval,temperature,windspeed,winddirection,is_day,weathercode
0,2026-06-25T12:45,900,31.4,13.1,172,1,0

# Nivell 3

### 1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [51]:
base = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

search = requests.get(f"{base}/package_search", params={
    "q": "transport"
})

results = search.json()
print(search.status_code)
print(len(results["result"]["results"]))

200
10

### 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [55]:
dataset = results["result"]["results"][0]

dataset_info = requests.get(
    f"{base}/package_show",
    params={"id": dataset["id"]}
)

data_json = dataset_info.json()

resources = data_json["result"]["resources"]

for r in resources:
    print(r["name"], r["format"], r["id"])

2026_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 3567ecde-a9d6-4478-b776-7872987fc6e6
2025_TransitAeri_FlightRadar_Ppal_Pais.csv CSV daaf92f4-8879-40f0-bc35-d550f1f9582a
2024_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 9b10dc6e-9266-4e33-935e-e10ed0dae343
2023_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 89cfba93-a038-4afe-adf5-599d879966d8
2022_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 1d78cf40-9d04-4be0-bcee-8e075c9a77a0
2021_TransitAeri_FlightRadar_Ppal_Pais.csv CSV c402f60b-5fb8-437a-bbbe-8976ac7ede51
2020_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 6d34a732-bdad-49e2-8231-7459120896d2
2019_TransitAeri_FlightRadar_Ppal_Pais.csv CSV 790b7bb3-cc2a-48d7-82c0-ef51978bceb7

### 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [53]:
resource_id = resources[0]["id"]

data = requests.get(
    f"https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search",
    params={
        "resource_id": resource_id,
        "limit": 100
    }
)

records = data.json()["result"]["records"]

### 4. Converteix els resultats a un DataFrame.

In [58]:
df_bcn = pd.DataFrame(records)
df_bcn.head()

       Data_Referencia    Nom_Pais Nombre_Vols  _id Codi_Pais
0  2026-01-01T00:00:00     Espanya         220    1         1
1  2026-01-01T00:00:00      Itàlia         110    2         2
2  2026-01-01T00:00:00  Regne Unit          80    3         3
3  2026-01-01T00:00:00      França          78    4         4
4  2026-01-01T00:00:00    Alemanya          49    5         5

### 5. Desa el DataFrame en un fitxer .csv.

In [63]:
df_bcn.to_csv("open_data_bcn.csv", index=False)
print("Guardado correctamente")

Guardado correctamente